[versions]
agp = "8.11.2"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
appcompat = "1.7.1"
material = "1.12.0"
javaxInjectVersion = "1"
hivemqVersion = "1.3.10"
orbitVersion = "10.0.0"
composeNavVersion = "2.9.6"
hiltVersion = "2.51.1"
hiltDaggerVerison = "2.55"
hiltComposeVersion = "1.0.0"
coilVersion = "2.5.0"
retrofitVersion = "2.9.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInjectVersion" }

hivemqtt = {module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemqVersion"}

orbit-viewmodel = {module = "org.orbit-mvi:orbit-core", version.ref = "orbitVersion"}
orbit-compose ={module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbitVersion"}
orbit-core = {module = "org.orbit-mvi:orbit-compose", version.ref = "orbitVersion"}

compose-navigation ={module = "androidx.navigation:navigation-compose", version.ref = "composeNavVersion"}

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltDaggerVerison" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltVersion" }
hilt-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltComposeVersion" }

coil-gif = {module ="io.coil-kt:coil-gif", version.ref = "coilVersion"}
coil-compose = {module ="io.coil-kt:coil-compose", version.ref = "coilVersion"}
coil-svg = {module ="io.coil-kt:coil-svg", version.ref = "coilVersion"}

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
retrofit-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofitVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android"}


